# Set up bash
# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 foldmethod=marker
---

- name:       install bash
  apt:
    name:     bash
    state:    installed

- name:       deploy system-wide bashrc
  copy:
    src:      "bash/bash.bashrc"
    dest:     "/etc/bash.bashrc"
    group:    root
    owner:    root
    mode:     0644

