# install additional debugging tools
# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 foldmethod=marker
---
- include_vars: debugtools.yaml
- apt: 
    name:       "{{ item }}"
    state:      present
  with_items:   "{{ debugpackages }}"
  when:         debugtools

- apt: 
    name:       "{{ item }}"
    state:      absent
  with_items:   "{{ debugpackages }}"
  when:         (not debugtools or debugtools is undefined)
