# install additional tools
# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 foldmethod=marker
---
- include_vars: extratools.yaml
- apt: 
    name:       "{{ item }}"
    state:      present
  with_items:   "{{ extrapackages }}"
  when:         extratools

- apt: 
    name:       "{{ item }}"
    state:      absent
  with_items:   "{{ extrapackages }}"
  when:         (not extratools or extratools is undefined)
