# Set up locale
# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 foldmethod=marker
---

- name:       install locales
  apt:
    name:     locales
    state:    installed

- name:       deploy locale.gen
  copy:
    src:      "locale/locale.gen"
    dest:     "/etc/locale.gen"
    group:    root
    owner:    root
    mode:     0644
  register:   localegen

- name:       generate locales
  command:    "/usr/sbin/locale-gen"
  when:       localegen|changed 

