# Set up cron-job to send reboot-mails
# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 foldmethod=marker
---

- name:           configure reboot-mail
  cron: 
    name:         mail-on-reboot
    user:         root
    special_time: reboot
    job:          "echo \"Reboot: `hostname -f` - `date` \"|mail -s \"Reboot: `hostname -f`\" your-mail-here`"
    cron_file:    rebootcron
