# Remove Users from all machines
# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 foldmethod=marker
---
- include_vars: removeusers.yaml

- name: remove users
  user: 
    name:         "{{ item }}"
    state:        "absent"
    remove:       "yes"
  with_items:     "{{ removeusers }}"
  tags:
    -rmusers

