# Set up resolv.conf
# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 foldmethod=marker
---

- name:       deploy resolv.conf
  template:
    src:      "resolvdotconf/resolv.conf.j2"
    dest:     "/etc/resolv.conf"
    group:    root
    owner:    root
    mode:     0644

